blueprints/demo.py
import json
import time
from datetime import datetime, timezone

from flask_login import current_user
from flask import Blueprint, render_template, request, redirect, url_for, send_from_directory
import requests

import helper
from Forecast import OpenWeatherMapForecasts
from app import app
from helper import page_data
from repositories.CityRepository import CityRepository

demo = Blueprint('demo', __name__)

cities = {
    "Ágios Stéfanos":2629,
    "Anávyssos":2710,
    "Dimos Chalandri":209077,
    "Dimos Athens":209095,
    "Dimos Kallithea":209098,
    "Dimos Lavreotiki":209127,
    "Dimos Markopoulo Mesogaias":209138,
    "Dimos Aspropyrgos":209148,
    "Peraía":19654,
    "Panórama":19666,
    "Koufália":19756,
    "Asvestochóri":19885,
    "Ássiros":19886,
    "Asproválta":19887,
    "Dimos Thessaloniki":209076,
}

@demo.route('/')
def index():
    city_repository = CityRepository()

    city = city_repository.find_city_by_id(209095)
    if 'city_id' in request.args:
        city = city_repository.find_city_by_id(request.args.get('city_id'))
        return redirect(url_for('demo.index')+"?city="+city.city, code=302)
    if 'city' in request.args and request.args.get('city') in cities:
        city = city_repository.find_city_by_id(cities[request.args.get('city')])

    coords_string = city.coords.replace("{", "")
    coords_string = coords_string.replace("}", "")
    coords_string = coords_string.split(",")
    lon = coords_string[0].split(":")[1].replace(" ", "")
    lat = coords_string[1].split(":")[1].replace(" ", "")
    selection = {'lat': lat, 'lon': lon, 'title': city.city}

    title = selection['title']

    owm_fetcher = OpenWeatherMapForecasts()
    weather = owm_fetcher.get_current_by_lat_lon(selection['lat'], selection['lon'])

    offset = time.timezone if (time.localtime().tm_isdst == 0) else time.altzone
    utc_diff_in_sec = (weather['timezone'] + offset)
    weather['dt'] = weather['dt'] + utc_diff_in_sec
    weather['dt'] = datetime.fromtimestamp(weather['dt'])

    forecast = owm_fetcher.get_forecast_by_lat_lon(selection['lat'], selection['lon'])
    custom_forecast = {}
    for day in forecast['list']:
        # print(day)
        date = datetime.fromtimestamp(day['dt'] + utc_diff_in_sec)
        day['dt'] = str(date)
        day['day_of_the_week'] = helper.day_of_the_week(date.weekday())
        day['main']['temp'] = round(day['main']['temp'])
        day['main']['temp_min'] = round(day['main']['temp_min'])
        day['main']['temp_max'] = round(day['main']['temp_max'])
        if not helper.day_of_the_week(date.weekday()) in custom_forecast:
            custom_forecast[helper.day_of_the_week(date.weekday())] = []
        temp_style = "background-color: #D3D3D3;"

        if day['main']['temp'] >= 35 and day['main']['temp'] <= 39:
            temp_style = 'background-color: #FFA500;font-weight: bold;'
        if day['main']['temp'] >= 40:
            temp_style = 'background-color: #FF0000;font-weight: bold;'
        custom_forecast[helper.day_of_the_week(date.weekday())].append({
            'icon': day['weather'][0]['icon'],
            'date': str(date.date()),
            'time': str(date.time())[:len(str(date.time())) - 3],
            'temp': day['main']['temp'],
            'temp_style': temp_style,
            'humidity': day['main']['humidity'],
            'wind_speed': day['wind']['speed'],
            'feels': day['main']['feels_like'],
            'description': day['weather'][0]['description']
        })

    attica_cities = city_repository.get_cities_by_region('Attica')
    theassaloniki_cities = city_repository.get_cities_by_region('Thessaloniki')

    return render_template('demo.html',
                           title=title,
                           weather=weather,
                           custom_forecast=custom_forecast,
                           attica_cities=attica_cities,
                           theassaloniki_cities=theassaloniki_cities,
                           page_data=page_data()
                           )


@demo.route('/contact')
def contact():
    city_repository = CityRepository()
    attica_cities = city_repository.get_cities_by_region('Attica')
    theassaloniki_cities = city_repository.get_cities_by_region('Thessaloniki')

    return render_template('contact.html',
                           title='Contact',
                           attica_cities=attica_cities,
                           theassaloniki_cities=theassaloniki_cities,
                           page_data=page_data()
                           )


@demo.route('/robots.txt')
@demo.route('/sitemap.xml')
def static_from_root():
    return send_from_directory(app.static_folder, request.path[1:])

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weather App - {{ title }}</title>
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='dist/img/weather_app.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

</head>
<body>
<div class="container">
    <nav class="navbar">
        <div class="logo">
            <a href="{{ url_for('demo.index') }}">
                <img width="40" height="40" src="{{ url_for('static', filename='dist/img/weather_app.png') }}"
                     alt="logo"/>
            </a>
            <span>Weather App</span>

        </div>
        <ul class="nav-links">
            <li class="dropdown">
                <a href="#" class="dropbtn">Attica</a>
                <div class="dropdown-content">
                    {% for attica_city in attica_cities %}
                        <a href="{{ url_for('demo.index') }}?city={{ attica_city.city }}">{{ attica_city['city'] }}</a>
                    {% endfor %}
                </div>
            </li>
            <li class="dropdown">
                <a href="#" class="dropbtn">Thessaloniki</a>
                <div class="dropdown-content">
                    {% for thessaloniki_city in theassaloniki_cities %}
                        <a href="{{ url_for('demo.index') }}?city={{ thessaloniki_city.city }}"
                           class="dropdown-item">{{ thessaloniki_city['city'] }}</a>
                    {% endfor %}
                </div>
            </li>
            <li><a href="{{ url_for('demo.contact') }}" class="contact-link">Contact</a></li>
        </ul>
    </nav>
    <header>
    </header>

    <main>
        {% block content %} {% endblock %}
    </main>

    <div id="status-message" class="hidden"></div>

    <footer class="footer">
        <div class="copyright">
            &copy; Copyright 2026 <a href="https://tkouleris.eu" class="footer-link">Thodoris Kouleris</a>, All rights
            reserved
        </div>
        <div class="powered-by">
            <span>Powered by </span>
            <img src="{{ url_for('static', filename='img/junie.jpg') }}" style="width: 50%;height: 30px;" alt="junie"/>
        </div>
    </footer>
</div>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-PWPHBBD1ZR"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'G-PWPHBBD1ZR');
</script>
</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% block content %}
    <!-- Main content -->
    <div class="content" style="margin-bottom: 20px;">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h1 class="m-0">Contact</h1>
                    You can contact me via the following methods:<br/>
                </div>
            </div>

            <div class="row">
                <div class="col-12"><b>email:</b> tkouleris@gmail.com</div>
            </div>
            <div class="row">
                <div class="col-12"><b>web:</b> <a target="_blank" class="generic-link" href="https://tkouleris.eu/">tkouleris.eu</a>
                </div>
            </div>
            <div class="row">
                <div class="col-12"><b>blog:</b> <a target="_blank" class="generic-link"
                                                    href="https://blog.tkouleris.eu/">blog.tkouleris.eu</a>
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->

    <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Android App</h1>
                </div><!-- /.col -->
                <div class="col-sm-12">
                    You can download the .apk file to install the app on your phone from <a class="generic-link"
                                                                                            href="https://drive.google.com/file/d/181NUMECk5tEgMd3UCVX_gu79h6-x3Yju/view?usp=drive_link">here</a>
                </div>
                <div class="col-sm-12" style="margin-top: 20px;">
                    <img src="{{ url_for('static', filename='dist/img/android/image_1.jpg') }}" alt="Android App"
                         style="height: 500px;margin-left: 10px;margin-right: 10px;">
                    <img src="{{ url_for('static', filename='dist/img/android/image_2.jpg') }}" alt="Android App"
                         style="height: 500px;">
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
{% endblock %}

templates/demo.html
{% extends "base.html" %}
{% block content %}
    <section class="current-weather">
        <div id="location-time" class="location-time">
                    <span class="location">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                             stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                            <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path>
                            <circle cx="12" cy="10" r="3"></circle>
                        </svg>
                        {{ weather['name'] }}
                    </span>
            <span class="separator">-</span>
            <span class="time">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                             stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                            <circle cx="12" cy="12" r="10"></circle>
                            <polyline points="12 6 12 12 16 14"></polyline>
                        </svg>
                        {{ weather['dt'] }}
                    </span>
        </div>

        <div class="main-info">

            <img id="current-icon"
                 src="https://openweathermap.org/img/wn/{{ weather['weather'][0]['icon'] }}@2x.png"
                 alt="Weather Icon" class="large-icon">
            <div id="current-temp" class="temp">{{ weather['main']['temp'] }}°C</div>
        </div>
        <div class="row" style="font-size: 12px;color: black;">
            Feels like {{ weather['main']['feels_like'] }}°C
        </div>
        <div class="details">
            <div class="detail-item">
                {#                    <span class="label">Humidity:</span>#}
                <span class="label">💧</span>
                <span id="current-humidity">{{ weather['main']['humidity'] }}%</span>
            </div>
            <div class="detail-item">
                {#                    <span class="label">Wind Speed:</span>#}
                <span class="label">💨</span>
                <span id="current-wind">{{ weather['wind']['speed'] }} m/s</span>
            </div>
        </div>
        <div id="current-description" class="description">
            {{ weather['weather'][0]['main'] }}, {{ weather['weather'][0]['description'] }}
        </div>
    </section>

    <section class="forecast">
        <h3>5-Day Forecast (Every 3 Hours)</h3>
        <div id="forecast-timeline" class="timeline">
            {% for day in custom_forecast %}
                <div class="forecast-day-row">
                    <h4>{{ day }}</h4>
                    <div class="day-items">
                        {% for data in custom_forecast[day] %}
                            <div class="forecast-item">
                                <div class="forecast-time">{{ data['time'] }}</div>
                                <img src="https://openweathermap.org/img/wn/{{ data['icon'] }}.png" alt="icon"
                                     class="forecast-icon">
                                <div class="forecast-temp">{{ data['temp'] }}°C</div>
                                <div class="forecast-description">{{ data['description'] }}</div>
                                <div class="forecast-details">
                                    <div>💧 {{ data['humidity'] }}%</div>
                                    <div>💨 {{ data['wind_speed'] }}m/s</div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}